title: ASmap.org

remote_theme: just-the-docs/just-the-docs@v0.8.2

plugins:
  - jekyll-remote-theme

nav_enabled: true
heading_anchors: true

header_pages:
  - background.md
  - data-sourcing.md
  - tools-and-resources.md
  - glossary.md
  - bitcoin-core.md
  - contributing.md

