title: ASmap.org

remote_theme: just-the-docs/just-the-docs@v0.8.2

plugins:
  - jekyll-remote-theme

nav_enabled: true
heading_anchors: true

nav_external_links:
  - title: Dashboard
    url: https://dashboard.asmap.org
    opens_in_new_tab: true
