title: ASmap.org

theme: just-the-docs

nav_enabled: true
heading_anchors: true

header_pages:
  - background.md
  - data-sourcing.md
  - tools-and-resources.md
  - glossary.md
  - bitcoin-core.md
  - contributing.md

