title: ASMap.org
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

header_pages:
  - background.md
  - data-sourcing.md
  - tools-and-resources.md
  - glossary.md
  - bitcoin-core.md
  - contributing.md

minima:
  skin: auto
